[package]
name = "SLiV9/my-game"
version = "1.0.0"
description = "A strategy game where you place troops, gather resources and follow imperial decrees."
readme = "README.md"
repository = "https://github.com/SLiV9/the-romans-are-coming"

[[module]]
name = "game"
source = "game.wasm"
abi = "wasm4"
interfaces = { wasm4 = "0.0.1" }

[[command]]
runner = "wasm4@0.0.1"
name = "play"
module = "game"
